import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Lam',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Bình hoa',
      slug: 'binh-hoa',
      category: 'Binh hoa',
      image: '/images/p1.jpg',
      price: 12,
      countInStock: 3,
      brand: 'QL',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '2',
      name: 'Ghế trắng',
      slug: 'ghe-trang',
      category: 'Ghe',
      image: '/images/p2.jpg',
      price: 22,
      countInStock: 30,
      brand: 'HL',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Sofa',
      slug: 'so-fa',
      category: 'Sofa',
      image: '/images/p3.jpg',
      price: 200,
      countInStock: 15,
      brand: 'HL',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Bàn Ăn',
      slug: 'ban-an',
      category: 'Ban an',
      image: '/images/p4.jpg',
      price: 300,
      countInStock: 0,
      brand: 'QL',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
